---
webservers:
  hosts:
    webserver.devops.org:
      ansible_user: root
      ansible_host: 192.168.100.10
    web2.devops.org:
      ansible_user: root
      ansible_connection: local  # Mark as unreachable
      ansible_host_is_down: true  # Custom variable to indicate maintenance
      ansible_host: 10.10.50.141

  vars:
    ignore_unreachable: true  # Ignore unreachable hosts in this group

ftpservers:
  hosts:
    ftp.devops.org:
      ansible_user: root
      ansible_host: 192.168.100.20
    ftp2.devops.org:
      ansible_user: root
      ansible_host: 192.168.100.50
monitoring:
  hosts:
    monitoring.devops.org:
      ansible_user: root
      ansible_host: 192.168.100.30

security:
  hosts:
    networksecurity.devops.org:
      ansible_user: root
      ansible_host: 192.168.100.40

all:
  children:
    servers:
      children:
        webservers:
        ftpservers:
        monitoring:
        security:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
