---
ftp_users:
  - username: ftpuser
    password: "{{ 'SecureFtpPass123' | password_hash('sha512') }}"
    local_root: /var/ftp/ftpuser
    chroot: yes
  - username: readonly
    password: "{{ 'ReadOnlyPass456' | password_hash('sha512') }}"
    local_root: /var/ftp/readonly
    chroot: yes
    write_access: no

ftp_banner: "Welcome to DevOps FTP Server"
anonymous_enable: no
local_enable: yes
write_enable: yes
chroot_local_user: yes
