---
- name: Rollback FTP Server Installation
  hosts: ftp.devops.org
  become: yes
  tasks:
    - name: Remove Webmin repository
      apt_repository:
        repo: deb http://download.webmin.com/download/repository sarge contrib
        state: absent
        filename: webmin
        
    - name: Remove Webmin repository key
      apt_key:
        id: D97A3AE911F63C51
        state: absent
        
    - name: Remove installed packages
      apt:
        name:
          - vsftpd
          - webmin
          - apache2
          - ftp
        state: absent
        autoremove: yes
        purge: yes
        
    - name: Remove FTP user
      user:
        name: ftpuser
        state: absent
        remove: yes
        
    - name: Remove FTP directory
      file:
        path: /home/ftpuser
        state: absent
